apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
  labels:
    app: restaurant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
      - name: restaurant
        image: cravely/restaurant:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003
        env:
        - name: PORT
          value: "5003"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: restaurant-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"